hakkoda_edw_shared:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ht48847.canada-central.azure

      # User/password auth
      user: HAKKODA_EDW_USER
      password: H@kk0da1

      role: HAKKODA_EDW_ROLE
      database: HAKKODA_EDW_DEV
      warehouse: HAKKODA_EDW_WH
      schema: dbt_hakkoda_edw
      threads: 8
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
